import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
import { CartProvider } from "@/context/CardContext";
import { WishListProvider } from "@/context/WishListContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bgimg">
          <div className="bg-white/60">

            <CartProvider>
              <WishListProvider>
            <Header />
                {children}</WishListProvider></CartProvider>
            <Footer />
          </div>{" "}
        </div>
      </body>
    </html>
  );
}
